"""Candidate-bounded LLM review after local evidence-pool contraction.

The hypergraph remains the primary diagnosis model. A training-fold local
organizer retains one fallback and at most one evidence-supported challenger;
the LLM reviews only that bounded pair and fails closed to the fallback.
"""

from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple, Union

import numpy as np

from hypergraph_core import LightweightHDiffusionClassifier


LLMClient = Callable[[Mapping[str, Any]], Union[Mapping[str, Any], str]]


@dataclass(frozen=True)
class EvidenceItem:
    """One immutable fact included in a candidate-bound review packet."""

    evidence_id: str
    kind: str
    summary: str
    root_labels: Tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.evidence_id or not self.kind or not self.summary:
            raise ValueError("evidence id, kind, and summary must be nonempty")
        if len(set(self.root_labels)) != len(self.root_labels):
            raise ValueError("evidence item root labels must be unique")

    def as_dict(self) -> Dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "kind": self.kind,
            "summary": self.summary,
            "root_labels": list(self.root_labels),
        }


@dataclass(frozen=True)
class CandidateRecord:
    """An existing root-set candidate generated by the fitted hypergraph."""

    candidate_id: str
    labels: Tuple[str, ...]

    def __post_init__(self) -> None:
        if not self.candidate_id or not self.labels or len(set(self.labels)) != len(self.labels):
            raise ValueError("candidate records require a nonempty unique label set")

    def as_dict(self) -> Dict[str, Any]:
        return {"candidate_id": self.candidate_id, "root_labels": list(self.labels)}


@dataclass(frozen=True)
class LLMReviewEvidence:
    """Compact training-grounded evidence for one bounded comparison."""

    query_items: Tuple[EvidenceItem, ...]
    training_items: Tuple[EvidenceItem, ...]
    mechanism_items: Tuple[EvidenceItem, ...]
    candidate_items: Tuple[EvidenceItem, ...] = ()
    semantic_items: Tuple[EvidenceItem, ...] = ()
    requires_direct_evidence: bool = False

    def __post_init__(self) -> None:
        all_items = self.items
        item_ids = [item.evidence_id for item in all_items]
        if not self.query_items or not self.training_items or not self.mechanism_items:
            raise ValueError("review evidence requires query, training, and mechanism facts")
        if len(item_ids) != len(set(item_ids)):
            raise ValueError("review evidence ids must be unique")
        expected = (
            (self.query_items, "query_metric_trajectory"),
            (self.training_items, "training_root_profile"),
            (self.mechanism_items, "mechanism_card"),
            (self.candidate_items, "candidate_evidence_card"),
            (self.semantic_items, "semantic_observation"),
        )
        if any(item.kind != kind for items, kind in expected for item in items):
            raise ValueError("review evidence has an unexpected kind")

    @property
    def items(self) -> Tuple[EvidenceItem, ...]:
        return (
            self.query_items
            + self.training_items
            + self.mechanism_items
            + self.candidate_items
            + self.semantic_items
        )

    def as_dict(self) -> Dict[str, Any]:
        return {
            "query_trajectory": [item.as_dict() for item in self.query_items],
            "outer_training_root_profiles": [item.as_dict() for item in self.training_items],
            "mechanism_cards": [item.as_dict() for item in self.mechanism_items],
            "candidate_evidence_cards": [item.as_dict() for item in self.candidate_items],
            "semantic_observations": [item.as_dict() for item in self.semantic_items],
            "requires_direct_evidence": self.requires_direct_evidence,
        }


@dataclass(frozen=True)
class ReviewResult:
    final_candidate_id: str
    suggested_candidate_id: Optional[str]
    status: str
    called: bool
    response_count: int
    reason_code: Optional[str] = None
    cited_evidence_ids: Tuple[str, ...] = ()
    relation_type: Optional[str] = None
    recommendation: Optional[str] = None


class CandidateBoundLLMReviewer:
    """One-call, fail-closed review of a pair of existing candidates.

    Callers retain a local structured candidate for failure handling, but the
    model sees two peer A/B records in a deterministic order.  It cannot create
    labels, inspect model scores, or infer unavailable SQL/plan context.
    """

    _ACTIONS = frozenset({"SELECT_CANDIDATE", "ABSTAIN"})
    _RELATIONS = frozenset({
        "COMPLEMENTARY",
        "COVERAGE",
        "REDUNDANT",
        "CONFLICT",
        "UNRESOLVED",
    })
    _RECOMMENDATIONS = frozenset({
        "RETAIN_COMPLEMENTARY_ROOTS",
        "PRUNE_COVERED_ROOTS",
        "PRUNE_REDUNDANT_ROOTS",
        "REPLACE_CONFLICTING_ROOTS",
        "NO_CHANGE",
    })
    _REASONS = frozenset(
        {"evidence_closure", "candidate_contradicted", "insufficient_evidence"}
    )
    _RESPONSE_KEYS = frozenset({
        "action", "candidate_id", "evidence_ids", "reason_code",
        "relation_type", "recommendation",
    })

    def __init__(
        self,
        client: Optional[LLMClient] = None,
        *,
        allow_override: bool = False,
        allowed_override_relations: Optional[Sequence[str]] = None,
    ) -> None:
        self.client = client
        self.allow_override = bool(allow_override)
        if allowed_override_relations is None:
            self.allowed_override_relations: Optional[frozenset[str]] = None
        else:
            relations = frozenset(allowed_override_relations)
            if not relations <= self._RELATIONS - {"UNRESOLVED"}:
                raise ValueError("override relation gate contains an unregistered relation")
            self.allowed_override_relations = relations

    @staticmethod
    def _parse_json(value: Mapping[str, Any] | str) -> Mapping[str, Any]:
        if isinstance(value, str):
            text = value.strip()
            if text.startswith("```"):
                lines = text.splitlines()
                if len(lines) >= 3 and lines[-1].strip() == "```":
                    text = "\n".join(lines[1:-1]).strip()
            value = json.loads(text)
        if not isinstance(value, Mapping):
            raise ValueError("LLM response must be a JSON object")
        return value

    @classmethod
    def _parse_response(cls, value: Mapping[str, Any] | str) -> Dict[str, Any]:
        result = dict(cls._parse_json(value))
        if set(result) != cls._RESPONSE_KEYS or result["action"] not in cls._ACTIONS:
            raise ValueError("LLM review response does not match the strict schema")
        if result["candidate_id"] is not None and not isinstance(result["candidate_id"], str):
            raise ValueError("candidate_id must be a string or null")
        if result["relation_type"] not in cls._RELATIONS:
            raise ValueError("LLM relation_type is not registered")
        if result["recommendation"] not in cls._RECOMMENDATIONS:
            raise ValueError("LLM recommendation is not registered")
        # The reason is an audit annotation, never an authority signal. Models
        # sometimes return a more descriptive phrase despite the enum in the
        # prompt; normalize that harmless variation while keeping the action,
        # candidate, and citation checks strict.
        if result["reason_code"] not in cls._REASONS:
            if not isinstance(result["reason_code"], str) or not result["reason_code"].strip():
                raise ValueError("reason_code must be a nonempty string")
            result["reason_code"] = (
                "evidence_closure"
                if result["action"] == "SELECT_CANDIDATE"
                else "insufficient_evidence"
            )
        ids = result["evidence_ids"]
        if not isinstance(ids, list) or not all(isinstance(item, str) and item for item in ids):
            raise ValueError("evidence_ids must be a list of nonempty strings")
        if len(ids) != len(set(ids)):
            raise ValueError("evidence_ids must not contain duplicates")
        result["evidence_ids"] = list(ids)
        return result

    @staticmethod
    def _candidate_slots(
        local: CandidateRecord, alternative: CandidateRecord
    ) -> Tuple[Tuple[str, CandidateRecord], ...]:
        """Assign stable A/B slots without exposing the caller's preference."""

        ordered = sorted(
            (local, alternative),
            key=lambda candidate: (tuple(sorted(candidate.labels)), candidate.candidate_id),
        )
        return tuple(zip(("A", "B"), ordered))

    @staticmethod
    def _matching_item(
        items: Sequence[EvidenceItem], root_labels: Sequence[str]
    ) -> EvidenceItem:
        target = frozenset(root_labels)
        matches = [item for item in items if frozenset(item.root_labels) == target]
        if len(matches) != 1:
            raise ValueError("review evidence does not contain one matching evidence card")
        return matches[0]

    @staticmethod
    def _redacted_summary(
        summary: str, slots: Sequence[Tuple[str, CandidateRecord]]
    ) -> str:
        result = summary
        for slot, candidate in slots:
            result = result.replace(candidate.candidate_id, f"candidate slot {slot}")
        return result

    @staticmethod
    def _set_relation(
        slots: Sequence[Tuple[str, CandidateRecord]],
    ) -> Dict[str, Any]:
        """Describe candidate-set topology before asking the LLM about evidence."""

        if len(slots) != 2:
            raise ValueError("relation review requires exactly two candidates")
        first = set(slots[0][1].labels)
        second = set(slots[1][1].labels)
        shared = sorted(first & second)
        only_first = sorted(first - second)
        only_second = sorted(second - first)
        if first < second:
            structural = "A_PROPER_SUBSET_OF_B"
        elif second < first:
            structural = "B_PROPER_SUBSET_OF_A"
        elif first & second:
            structural = "PARTIAL_OVERLAP"
        else:
            structural = "DISJOINT"
        return {
            "set_relation": structural,
            "shared_roots": shared,
            "only_A": only_first,
            "only_B": only_second,
        }

    @classmethod
    def _valid_relation_decision(
        cls,
        response: Mapping[str, Any],
        slots: Sequence[Tuple[str, CandidateRecord]],
    ) -> bool:
        relation = response["relation_type"]
        recommendation = response["recommendation"]
        if response["action"] == "ABSTAIN":
            return relation == "UNRESOLVED" and recommendation == "NO_CHANGE"
        chosen = set(next(candidate for slot, candidate in slots if slot == response["candidate_id"]).labels)
        first = set(slots[0][1].labels)
        second = set(slots[1][1].labels)
        if relation == "COMPLEMENTARY":
            superset = first | second
            return (
                (first < second or second < first)
                and chosen == superset
                and recommendation == "RETAIN_COMPLEMENTARY_ROOTS"
            )
        if relation == "COVERAGE":
            subset = first if first < second else second if second < first else None
            return subset is not None and chosen == subset and recommendation == "PRUNE_COVERED_ROOTS"
        if relation == "REDUNDANT":
            subset = first if first < second else second if second < first else None
            return subset is not None and chosen == subset and recommendation == "PRUNE_REDUNDANT_ROOTS"
        if relation == "CONFLICT":
            return (
                recommendation == "REPLACE_CONFLICTING_ROOTS"
                and chosen in (first, second)
                and bool(first ^ second)
            )
        return False

    @classmethod
    def _review_packet(
        cls,
        local: CandidateRecord,
        alternative: CandidateRecord,
        evidence: LLMReviewEvidence,
    ) -> Tuple[
        Dict[str, Any],
        Dict[str, CandidateRecord],
        frozenset[str],
        frozenset[str],
        Tuple[Tuple[str, CandidateRecord], ...],
        frozenset[str],
        Mapping[str, frozenset[str]],
    ]:
        """Build the anonymous packet and its deterministic citation contract."""

        slots = cls._candidate_slots(local, alternative)
        slot_candidates = dict(slots)
        relation = cls._set_relation(slots)
        distinguishing_roots = tuple(
            sorted(set(local.labels).symmetric_difference(alternative.labels))
        )
        candidate_cards = tuple(
            (slot, cls._matching_item(evidence.candidate_items, candidate.labels))
            for slot, candidate in slots
        )
        profiles = tuple(
            cls._matching_item(evidence.training_items, (label,))
            for label in distinguishing_roots
        )
        mechanisms = tuple(
            cls._matching_item(evidence.mechanism_items, (label,))
            for label in distinguishing_roots
        )

        public_items: Dict[str, EvidenceItem] = {}

        def expose(
            item: EvidenceItem, citation_id: str, candidate_slot: Optional[str] = None
        ) -> Dict[str, Any]:
            if citation_id in public_items:
                raise RuntimeError("review citation ids must be unique")
            public_items[citation_id] = item
            payload_item: Dict[str, Any] = {
                "evidence_id": citation_id,
                "kind": item.kind,
                "summary": cls._redacted_summary(item.summary, slots),
                "root_labels": list(item.root_labels),
            }
            if candidate_slot is not None:
                payload_item["candidate_id"] = candidate_slot
            return payload_item

        query_records = tuple(
            expose(item, f"query-{index:02d}")
            for index, item in enumerate(evidence.query_items, start=1)
        )
        profile_records = tuple(
            expose(item, f"profile-{index:02d}")
            for index, item in enumerate(profiles, start=1)
        )
        mechanism_records = tuple(
            expose(item, f"mechanism-{index:02d}")
            for index, item in enumerate(mechanisms, start=1)
        )
        candidate_records = tuple(
            expose(item, f"candidate-card-{slot}", candidate_slot=slot)
            for slot, item in candidate_cards
        )
        semantic_records = tuple(
            expose(item, f"semantic-{index:02d}")
            for index, item in enumerate(evidence.semantic_items, start=1)
        )
        direct_semantic_ids = frozenset(
            item["evidence_id"]
            for item in semantic_records
            if item["kind"] == "semantic_observation"
            and bool(set(item["root_labels"]) & set(distinguishing_roots))
            and (
                item["summary"].startswith("Direct candidate-discriminating")
                or item["summary"].startswith(
                    "Strong cross-group training-associated candidate-discriminating"
                )
            )
        )
        semantic_support_by_id = {
            item["evidence_id"]: frozenset(item["root_labels"])
            for item in semantic_records
            if item["evidence_id"] in direct_semantic_ids
        }
        # Query and both candidate cards establish the common factual basis.
        required_ids = frozenset(
            item["evidence_id"]
            for records in (query_records, candidate_records)
            for item in records
        )
        payload = {
            "task": "symmetric_candidate_evidence_review",
            "candidate_relation": relation,
            "candidate_records": [
                {"candidate_id": slot, "root_labels": list(candidate.labels)}
                for slot, candidate in slots
            ],
            "evidence": {
                "query_trajectory": list(query_records),
                "root_profiles": list(profile_records),
                "mechanism_cards": list(mechanism_records),
                "candidate_evidence_cards": list(candidate_records),
                "semantic_observations": list(semantic_records),
            },
            "requires_direct_semantic_evidence": evidence.requires_direct_evidence,
        }
        return (
            payload,
            slot_candidates,
            frozenset(public_items),
            required_ids,
            slots,
            direct_semantic_ids,
            semantic_support_by_id,
        )

    @staticmethod
    def _valid_selection(
        response: Mapping[str, Any],
        slot_candidates: Mapping[str, CandidateRecord],
        valid_ids: frozenset[str],
        required_ids: frozenset[str],
        slots: Sequence[Tuple[str, CandidateRecord]],
        direct_semantic_ids: frozenset[str],
        semantic_support_by_id: Mapping[str, frozenset[str]],
        requires_direct_evidence: bool,
    ) -> bool:
        cited = frozenset(response["evidence_ids"])
        cited_semantic_roots = frozenset(
            root
            for evidence_id in cited & direct_semantic_ids
            for root in semantic_support_by_id.get(evidence_id, ())
        )
        chosen_roots = frozenset(
            slot_candidates[response["candidate_id"]].labels
        ) if response["candidate_id"] in slot_candidates else frozenset()
        family_ids = frozenset(
            evidence_id
            for evidence_id in valid_ids
            if evidence_id.startswith("profile-") or evidence_id.startswith("mechanism-")
        )
        candidate_card_ids = frozenset(
            evidence_id for evidence_id in valid_ids if evidence_id.startswith("candidate-card-")
        )
        return (
            response["candidate_id"] in slot_candidates
            and response["reason_code"] != "insufficient_evidence"
            and required_ids <= cited <= valid_ids
            and len(cited & candidate_card_ids) == len(candidate_card_ids)
            and bool(cited & family_ids)
            and (
                not requires_direct_evidence
                or (
                    bool(direct_semantic_ids)
                    and bool(cited & direct_semantic_ids)
                    and bool(cited_semantic_roots)
                    and cited_semantic_roots <= chosen_roots
                )
            )
            and CandidateBoundLLMReviewer._valid_relation_decision(response, slots)
        )

    def review(
        self,
        local: CandidateRecord,
        alternative: Optional[CandidateRecord],
        evidence: Optional[LLMReviewEvidence],
    ) -> ReviewResult:
        def fallback(
            status: str,
            *,
            called: bool = False,
            response_received: bool = False,
            suggested: Optional[str] = None,
        ) -> ReviewResult:
            return ReviewResult(
                local.candidate_id,
                suggested,
                status,
                called,
                int(response_received),
            )

        if self.client is None:
            return fallback("disabled_no_client")
        if alternative is None:
            return fallback("skipped_no_structured_conflict")
        if alternative.candidate_id == local.candidate_id:
            raise ValueError("local and alternative candidates must differ")
        if evidence is None:
            return fallback("skipped_no_review_evidence")
        try:
            (
                payload,
                slot_candidates,
                valid_ids,
                required_ids,
                slots,
                direct_semantic_ids,
                semantic_support_by_id,
            ) = self._review_packet(
                local, alternative, evidence
            )
        except (RuntimeError, ValueError):
            return fallback("skipped_incomplete_review_evidence")
        if evidence.requires_direct_evidence and not direct_semantic_ids:
            return fallback("skipped_no_direct_semantic_evidence")
        try:
            response = self._parse_response(self.client(payload))
        except json.JSONDecodeError:
            return fallback("fallback_invalid_json_review", called=True, response_received=True)
        except (KeyError, TypeError, ValueError):
            return fallback("fallback_invalid_review", called=True, response_received=True)
        except Exception:
            return fallback("fallback_transport_or_timeout", called=True)
        cited = tuple(sorted(response["evidence_ids"]))
        action = response["action"]
        if action == "ABSTAIN":
            # Abstention can never replace the local candidate.  Accept a
            # slightly over-specified abstention rather than treating it as a
            # transport failure; its extra citations have no decision effect.
            return ReviewResult(
                local.candidate_id,
                None,
                "accepted_abstain",
                True,
                1,
                "insufficient_evidence",
                (),
                "UNRESOLVED",
                "NO_CHANGE",
            )
        if not self._valid_selection(
            response,
            slot_candidates,
            valid_ids,
            required_ids,
            slots,
            direct_semantic_ids,
            semantic_support_by_id,
            evidence.requires_direct_evidence,
        ):
            return fallback(
                "fallback_invalid_candidate_selection",
                called=True,
                response_received=True,
            )
        selected = slot_candidates[response["candidate_id"]]
        relation_approved = (
            self.allowed_override_relations is None
            or response["relation_type"] in self.allowed_override_relations
        )
        if selected.candidate_id != local.candidate_id and not (
            self.allow_override and relation_approved
        ):
            return ReviewResult(
                local.candidate_id,
                selected.candidate_id,
                "audited_candidate_selection_without_override",
                True,
                1,
                response["reason_code"],
                cited,
                response["relation_type"],
                response["recommendation"],
            )
        return ReviewResult(
            selected.candidate_id,
            selected.candidate_id,
            "accepted_candidate_selection",
            True,
            1,
            response["reason_code"],
            cited,
            response["relation_type"],
            response["recommendation"],
        )


class HyperDBDiagPipeline:
    """Hypergraph prediction, local candidate selection, and optional LLM review."""

    def __init__(
        self,
        labels: Sequence[str],
        metric_model: Optional[LightweightHDiffusionClassifier] = None,
        llm_reviewer: Optional[CandidateBoundLLMReviewer] = None,
        llm_max_workers: int = 4,
    ) -> None:
        if not labels or len(set(labels)) != len(labels):
            raise ValueError("root label inventory must be nonempty and unique")
        if int(llm_max_workers) < 1:
            raise ValueError("LLM worker count must be positive")
        self.labels = tuple(labels)
        self.metric_model = metric_model or LightweightHDiffusionClassifier()
        self.llm_reviewer = llm_reviewer or CandidateBoundLLMReviewer()
        self.llm_max_workers = int(llm_max_workers)

    def fit(
        self,
        vectors: np.ndarray,
        train_labels: Sequence[Sequence[str]],
        oof_groups: Sequence[int],
        semantic_observations: Optional[Sequence[Sequence[Any]]] = None,
    ) -> "HyperDBDiagPipeline":
        self.metric_model.fit(
            vectors,
            train_labels,
            self.labels,
            oof_groups,
            semantic_observations,
        )
        return self

    def _candidate_inventory(self) -> Tuple[CandidateRecord, ...]:
        return tuple(
            CandidateRecord(
                candidate_id=f"candidate-{index:03d}",
                labels=tuple(self.labels[root] for root in roots),
            )
            for index, roots in enumerate(self.metric_model.candidates)
        )

    @staticmethod
    def _candidate_rows(
        values: Optional[Sequence[Optional[int]]], count: int, limit: int, name: str
    ) -> List[Optional[int]]:
        if values is None:
            return [None] * count
        result = list(values)
        if len(result) != count:
            raise ValueError(f"{name} and metric observation counts differ")
        if any(value is not None and (not isinstance(value, (int, np.integer)) or not 0 <= int(value) < limit) for value in result):
            raise ValueError(f"{name} contains an invalid candidate index")
        return [None if value is None else int(value) for value in result]

    def predict_details(
        self,
        vectors: np.ndarray,
        evidence_by_observation: Optional[Sequence[LLMReviewEvidence]] = None,
        local_candidate_indices: Optional[Sequence[int]] = None,
        alternative_candidate_indices: Optional[Sequence[Optional[int]]] = None,
        predictor_semantic_observations: Optional[Sequence[Sequence[Any]]] = None,
    ) -> List[Dict[str, Any]]:
        probabilities = self.metric_model.predict_proba(
            vectors, predictor_semantic_observations
        )
        inventory = self._candidate_inventory()
        count = len(probabilities)
        if evidence_by_observation is None:
            bundles: List[Optional[LLMReviewEvidence]] = [None] * count
        else:
            bundles = list(evidence_by_observation)
            if len(bundles) != count or any(not isinstance(bundle, LLMReviewEvidence) for bundle in bundles):
                raise ValueError("review evidence and metric observations differ")
        hypergraph_indices = [int(index) for index in np.argmax(probabilities, axis=1)]
        local_indices = self._candidate_rows(
            local_candidate_indices, count, len(inventory), "local candidate indices"
        )
        local_indices = [
            hypergraph if local is None else local
            for hypergraph, local in zip(hypergraph_indices, local_indices)
        ]
        alternative_indices = self._candidate_rows(
            alternative_candidate_indices, count, len(inventory), "alternative candidate indices"
        )
        local_rows = [inventory[index] for index in local_indices]
        alternative_rows = [
            None if index is None or index == local_index else inventory[index]
            for index, local_index in zip(alternative_indices, local_indices)
        ]
        requests = list(zip(local_rows, alternative_rows, bundles))
        if self.llm_reviewer.client is None or len(requests) < 2 or self.llm_max_workers == 1:
            results = [self.llm_reviewer.review(local, alternative, evidence) for local, alternative, evidence in requests]
        else:
            with ThreadPoolExecutor(max_workers=min(self.llm_max_workers, len(requests))) as executor:
                results = list(
                    executor.map(
                        lambda item: self.llm_reviewer.review(item[0], item[1], item[2]), requests
                    )
                )
        by_id = {candidate.candidate_id: candidate for candidate in inventory}
        details: List[Dict[str, Any]] = []
        for hypergraph_index, local, alternative, result in zip(
            hypergraph_indices, local_rows, alternative_rows, results
        ):
            final = by_id[result.final_candidate_id]
            details.append(
                {
                    "predicted_labels": list(final.labels),
                    "hypergraph_labels": list(inventory[hypergraph_index].labels),
                    "hypergraph_candidate_id": inventory[hypergraph_index].candidate_id,
                    "local_labels": list(local.labels),
                    "local_candidate_id": local.candidate_id,
                    "alternative_candidate_id": None if alternative is None else alternative.candidate_id,
                    "llm_status": result.status,
                    "llm_called": result.called,
                    "llm_response_count": result.response_count,
                    "llm_suggested_candidate_id": result.suggested_candidate_id,
                    "llm_reason_code": result.reason_code,
                    "llm_cited_evidence_ids": list(result.cited_evidence_ids),
                    "llm_relation_type": result.relation_type,
                    "llm_recommendation": result.recommendation,
                }
            )
        return details

    def predict(
        self,
        vectors: np.ndarray,
        evidence_by_observation: Optional[Sequence[LLMReviewEvidence]] = None,
        local_candidate_indices: Optional[Sequence[int]] = None,
        alternative_candidate_indices: Optional[Sequence[Optional[int]]] = None,
        predictor_semantic_observations: Optional[Sequence[Sequence[Any]]] = None,
    ) -> List[List[str]]:
        return [
            list(row["predicted_labels"])
            for row in self.predict_details(
                vectors,
                evidence_by_observation,
                local_candidate_indices,
                alternative_candidate_indices,
                predictor_semantic_observations,
            )
        ]

    def metadata(self) -> Dict[str, Any]:
        return {
            "metric_candidate_source": "training-fold lightweight hypergraph",
            "candidate_inventory_size": len(self.metric_model.candidates),
            "review_protocol": "symmetric A/B ECSA relation review of two existing candidate-bound records",
            "llm_policy": {
                "client_configured": self.llm_reviewer.client is not None,
                "allow_override": self.llm_reviewer.allow_override,
                "allowed_override_relations": (
                    None
                    if self.llm_reviewer.allowed_override_relations is None
                    else sorted(self.llm_reviewer.allowed_override_relations)
                ),
                "bounded_parallel_workers": self.llm_max_workers,
                "action_budget": "assess complementarity, coverage, redundancy, or conflict; select candidate A or B, or abstain",
                "failure_policy": "return the local structured candidate",
            },
            "remediation_policy": {
                "authority": "post-diagnosis advice only",
                "changes_predictions": False,
                "allowed_actions": "read-only plan, predicate/index, lock-chain, or query-shape review",
                "failure_policy": "return NO_ACTIONABLE_RECOMMENDATION",
            },
        }
